services:
  postgres:
    image: postgres:17-alpine
    container_name: postgres_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: balances
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready -U admin -d balances' ]
      interval: 3s
      timeout: 5s
      retries: 5
      start_period: 5s
  app:
    build: .
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8000:8000"
    environment:
      DB_NAME: balances
      DB_USER: admin
      DB_PASSWORD: admin
      DB_HOST: postgres
      DB_PORT: 5432
    restart: always
volumes:
  pgdata:
    driver: local